function PP = Realign_parameter(PP)
%% update: 20251107
% ProcessMotionParameters - Process motion parameters for all subjects

fprintf(['\nRealign Parameter Calculate Starting    ||    ' spm('time') '\n']);

DataList = PP.DataList;

% Create main RP and QC directories
RP_Path = fullfile(DataList.dataroot_path, 'RealignParameter');
QC_Path = fullfile(DataList.dataroot_path, 'QC');

% Remove and recreate main directories
if exist(RP_Path, 'dir')
    rmdir(RP_Path, 's');
end
mkdir(RP_Path);

if exist(QC_Path, 'dir')
    rmdir(QC_Path, 's');
end
mkdir(QC_Path);

% Initialize RMS structure
RMS = struct();

for i = 1:length(PP.RefEcho_Para.RefFun_list)
    % Generate input parameters with subject subfolders
    Fun_src_Path = fileparts(PP.RefEcho_Para.RefFun_list{i});
    sub = DataList.Sublist{PP.RefEcho+PP.Enum * (i-1)};
    RP_dst_Path = fullfile(RP_Path, sub);
    QC_dst_Path = fullfile(QC_Path, sub);

    % Remove and recreate subject directories
    if exist(RP_dst_Path, 'dir')
        rmdir(RP_dst_Path, 's');
    end
    mkdir(RP_dst_Path);
    
    if exist(QC_dst_Path, 'dir')
        rmdir(QC_dst_Path, 's');
    end
    mkdir(QC_dst_Path);
    
    % Process motion parameters
    [Max_Translation, Max_Rotation, Max_displacement] = rm_file_and_calc_rms(Fun_src_Path, RP_dst_Path, QC_dst_Path);
    
    % Store results
    RMS(i).SID = sub;
    RMS(i).MAX = [Max_Translation, Max_Rotation, Max_displacement];
    clear Max_Translation Max_Rotation Max_displacement sub
end

% Generate subjects_remove_criteria.txt
[maxMotion_txtPath] = maxMotionText(RMS, QC_Path);

% Update PP structure
PP.RP_Path = RP_Path;
PP.QC_Path = QC_Path;

fprintf(['\nRealign Parameter Generated    ||    ' spm('time') '\n']);
end

function [Max_Translation, Max_Rotation, Max_displacement] = rm_file_and_calc_rms(Fun_src_Path, RP_dst_Path, QC_dst_Path)
    % ---------- Move Some Files ----------
    [a,b,~]=fileparts(RP_dst_Path);
    if contains(b, 'Echo', 'IgnoreCase', true)
        RP_dst_Path = a;
    end
    movefile([Fun_src_Path filesep 'mean*'], RP_dst_Path);
    movefile([Fun_src_Path filesep 'rp*'], RP_dst_Path);
    movefile([Fun_src_Path filesep '*.mat'], RP_dst_Path);

    % ---------- Calc. rms ----------
    DirList4RegExp = dir([RP_dst_Path filesep 'rp*']);
    rpfilepath = [RP_dst_Path filesep DirList4RegExp.name]; clear DirList4RegExp

    Ref_name = dir([RP_dst_Path filesep 'mean*']);
    Ref_Path = [RP_dst_Path filesep Ref_name.name]; clear Ref_name

    [Max_Translation, Max_Rotation] = motion_curve_plot(rpfilepath, QC_dst_Path);
    
    [rel_rms, abs_rms] = rp_y_FD_Jenkinson(rpfilepath, Ref_Path);
    rms = [rel_rms, abs_rms];
    save([RP_dst_Path filesep 'rms' '.txt'], 'rms', '-ASCII', '-DOUBLE','-TABS');

    rmsfilepath = [RP_dst_Path filesep 'rms.txt'];
    [Max_displacement] = rms_curve_plot(rmsfilepath, QC_dst_Path);

end

%%
function [Max_Translation, Max_Rotation]=motion_curve_plot(rpfilepath,Pictures_path)

data=load(rpfilepath);

Max_HeadMotion=max(abs(data));
Max_HeadMotion(4:6)=Max_HeadMotion(4:6)*180/pi;

Max_Translation=max(Max_HeadMotion(1:3));
Max_Rotation=max(Max_HeadMotion(4:6));

h1=figure('Visible', 'off');
plot(data(:,1),'b','LineWidth',1.5);
hold on
plot(data(:,2),'g','LineWidth',1.5);
hold on
plot(data(:,3),'r','LineWidth',1.5);
grid on
title('Translation')
xlabel('Repetition')
ylabel('mm')
legend('X','Y','Z')
set(gca,'xlim',[0 size(data,1)]);
hold off

h2=figure('Visible', 'off');
plot(data(:,4)*180/pi,'b','LineWidth',1.5);
hold on
plot(data(:,5)*180/pi,'g','LineWidth',1.5);
hold on
plot(data(:,6)*180/pi,'r','LineWidth',1.5);
grid on
title('Rotation')
xlabel('Repetition')
ylabel('degree')
legend('Pitch','Yaw','Roll')
set(gca,'xlim',[0 size(data,1)]);
hold off

motion_name1=strcat(Pictures_path,'\Translation.tif');
motion_name2=strcat(Pictures_path,'\Rotation.tif');

saveas(h1,motion_name1);
saveas(h2,motion_name2);

close(h1);
close(h2);
end

%%
function [rel_rms, abs_rms] = rp_y_FD_Jenkinson(RealignmentParameterFile,ReferenceImage)

% function [rel_rms, abs_rms] = y_FD_Jenkinson(RealignmentParameterFile,ReferenceImage)
% Calculate FD Jenkinson (relative RMS) and absolute RMS based on SPM's realignment parameters
% Reference: Jenkinson, M., Bannister, P., Brady, M., Smith, S., 2002. Improved optimization for the robust and accurate linear registration and motion correction of brain images. Neuroimage 17, 825-841.
%            Jenkinson, M. 1999. Measuring transformation error by RMS deviation. Internal Technical Report TR99MJ1, FMRIB Centre, University of Oxford. Available at www.fmrib.ox.ac.uk/analysis/techrep for downloading.
% Input:
% 	RealignmentParameterFile  -   The realignment parameter file for a given participant generated by SPM. E.g., rp***.txt
%   ReferenceImage            -   The reference image for realignment (usually the first time point (one-pass) or the mean image after an initial motion correction (two-pass))
% Output:
%	rel_rms      -   relative RMS (FD Jenkinson)
%	abs_rms      -   absolute RMS
%-----------------------------------------------------------
% Written by YAN Chao-Gan 120930.
% The Nathan Kline Institute for Psychiatric Research, 140 Old Orangeburg Road, Orangeburg, NY 10962, USA
% Child Mind Institute, 445 Park Avenue, New York, NY 10022, USA
% The Phyllis Green and Randolph Cowen Institute for Pediatric Neuroscience, New York University Child Study Center, New York, NY 10016, USA
% ycg.yan@gmail.com


rmax = 80.0; %The default radius (as in FSL) of a sphere represents the brain

RP=load(RealignmentParameterFile);
nTimePoint=size(RP,1);
sinq1=sin(RP(:,4));
sinq2=sin(RP(:,5));
sinq3=sin(RP(:,6));
cosq1=cos(RP(:,4));
cosq2=cos(RP(:,5));
cosq3=cos(RP(:,6));

[RefData,VoxDim,RefHead]=rp_readfile(ReferenceImage);

center = RefHead.mat*([0.5*(RefHead.dim(1));0.5*(RefHead.dim(2));0.5*(RefHead.dim(3));1]);
center = center(1:3); %Get the coordinate for the center

abs_rms = zeros(nTimePoint,1);
for t=1:nTimePoint
    
    M1=[1       0        0     0;...
        0    cosq1(t)  sinq1(t)  0;...
        0    -sinq1(t) cosq1(t)  0;...
        0       0        0     1;];
    
    M2=[cosq2(t)  0    sinq2(t)     0;...
        0        1       0        0;...
        -sinq2(t) 0    cosq2(t)     0;...
        0       0        0        1;];
    
    M3=[cosq3(t)   sinq3(t)   0     0;...
        -sinq3(t)  cosq3(t)   0     0;...
        0           0       1     0;...
        0           0       0     1;];
    
    MT=[1    0     0     RP(t,1);...
        0    1     0     RP(t,2);...
        0    0     1     RP(t,3);...
        0    0     0     1;];
    
    M_RigidBodyTransform=MT*M1*M2*M3;
    
    MA1=eye(4);
    MA2=(M_RigidBodyTransform);
    
    M = MA1*inv(MA2) - eye(4);
    
    A = M(1:3,1:3);
    
    T = M(1:3,4);
    
    abs_rms(t) = sqrt(rmax*rmax/5*trace(A'*A) + (T+A*center)'*(T+A*center));
end


rel_rms = zeros(nTimePoint-1,1);
for t=2:nTimePoint
    M1=[1       0        0     0;...
        0    cosq1(t)  sinq1(t)  0;...
        0    -sinq1(t) cosq1(t)  0;...
        0       0        0     1;];
    
    M2=[cosq2(t)  0    sinq2(t)     0;...
        0        1       0        0;...
        -sinq2(t) 0    cosq2(t)     0;...
        0       0        0        1;];
    
    M3=[cosq3(t)   sinq3(t)   0     0;...
        -sinq3(t)  cosq3(t)   0     0;...
        0           0       1     0;...
        0           0       0     1;];
    
    MT=[1    0     0     RP(t,1);...
        0    1     0     RP(t,2);...
        0    0     1     RP(t,3);...
        0    0     0     1;];
    
    M_RigidBodyTransform=MT*M1*M2*M3;
    
    
    M1=[1       0        0     0;...
        0    cosq1(t-1)  sinq1(t-1)  0;...
        0    -sinq1(t-1) cosq1(t-1)  0;...
        0       0        0     1;];
    
    M2=[cosq2(t-1)  0    sinq2(t-1)     0;...
        0        1       0        0;...
        -sinq2(t-1) 0    cosq2(t-1)     0;...
        0       0        0        1;];
    
    M3=[cosq3(t-1)   sinq3(t-1)   0     0;...
        -sinq3(t-1)  cosq3(t-1)   0     0;...
        0           0       1     0;...
        0           0       0     1;];
    
    MT=[1    0     0     RP(t-1,1);...
        0    1     0     RP(t-1,2);...
        0    0     1     RP(t-1,3);...
        0    0     0     1;];
    
    M_RigidBodyTransform_1=MT*M1*M2*M3;
    
    MA1=(M_RigidBodyTransform_1);
    MA2=(M_RigidBodyTransform);
    
    M = MA1*inv(MA2) - eye(4);
    
    A = M(1:3,1:3);
    
    T = M(1:3,4);
    
    rel_rms(t-1) = sqrt(rmax*rmax/5*trace(A'*A) + (T+A*center)'*(T+A*center));
    
end

rel_rms=[0;rel_rms]; %The FD_Jenkinson at time point t means the movement from time point t-1 to time point t. (Put the FD_Jenkinson for the first time point to "0".)
end

%%
function [Max_displacement]=rms_curve_plot(rmsfilepath,Pictures_path)

data=load(rmsfilepath);

Max_displacement=max(abs(data(:,2)));

h=figure('Visible', 'off');
plot(data(:,1),'b','LineWidth',1.5);
hold on
plot(data(:,2),'g','LineWidth',1.5);

grid on
title('Displacement')
xlabel('Repetition')
ylabel('mm')
legend('relative','absolute');
set(gca,'xlim',[0 size(data,1)]);

motion_name=strcat(Pictures_path,'\rms.tif');
saveas(h,motion_name);

close(h);
end

