function applyReorientMatrixCorrected(MatMatrix, niiFile)
% applyReorientMatrixCorrected  Correctly applies the transformation matrix saved by SPM
%                               (usually a translation) to a NIfTI image (supports 4D)
%   Inputs:
%       matFile - String, path to the .mat file containing a saved 4x4 affine matrix
%                 (typically generated by spm_image's Reorient)
%       niiFile - String, path to the NIfTI image to be transformed (.nii)
%
%   Function: Reads the target image's original voxel-to-world matrix (orig_mat),
%             reads the transformation matrix M, computes the new affine matrix
%             new_mat = M * orig_mat, and then writes it back to the image header.
%             This only adjusts the origin position while preserving the original
%             voxel size and orientation.
%
%   Notes:
%       - This function directly modifies the header of niiFile. The operation is
%         irreversible, so be sure to back up the original file first.
%       - Requires SPM12 to be on the MATLAB path.
%       - Supports 4D NIfTI files (the same transformation is applied to all time points).
%       - Does not support compressed files (.nii.gz); please decompress first.

if isempty(MatMatrix)
    error('Transformation matrix is empty');
end
if ~exist(niiFile, 'file')
    error('NIfTI image file does not exist: %s', niiFile);
end

[~, ~, ext] = fileparts(niiFile);
if strcmpi(ext, '.gz')
    error('Compressed files (.nii.gz) are not supported. Please decompress to a .nii file first.');
end

M = MatMatrix;

fprintf('Reading original image affine matrix: %s\n', niiFile);
V = spm_vol(niiFile);

numVol = numel(V);

orig_mat = V(1).mat; 

new_mat = M * orig_mat;

spm_get_space(niiFile, new_mat);

end